Insert into Medication values ('m-01', 'Abarelix ','Plenaxis');
Insert into Medication values ('m-02', 'Abatacept ','Orencia');
Insert into Medication values ('m-03', 'Abciximab ','ReoPro');
Insert into Medication values ('m-04', 'Abelcet  ','Amphotericin');
Insert into Medication values ('m-05', 'Abilify ','Aripiprazole');
Insert into Medication values ('m-06', 'Zytiga','Abiraterone ');
Insert into Medication values ('m-07', 'Ablavar ','Gadofosveset ');
Insert into Medication values ('m-08', 'Abobotulinumtoxin ','Dysport');
Insert into Medication values ('m-09', 'Abraxane ','Albumin-bound');
Insert into Medication values ('m-10', 'Acamprosate Calcium ','Campral');
Insert into Medication values ('m-11', 'Bacitracin','Bacitracin');
Insert into Medication values ('m-12', 'Baclofen Tablets','Baclofen');
Insert into Medication values ('m-13', 'Bacteriostatic Saline','Bacteriostatic NaCl ');
Insert into Medication values ('m-14', 'Bactrim ','Trimethoprim ');
Insert into Medication values ('m-15', 'Bactroban Cream ','Mupirocin Calcium Cream');
Insert into Medication values ('m-16', 'Bactroban Nasal ','Mupirocin Calcium Ointment');
Insert into Medication values ('m-17', 'Bactroban Ointment ','Mupirocin');
Insert into Medication values ('m-18', 'Bal in Oil Ampules ','Dimercarprol Injection');
Insert into Medication values ('m-19', 'Balanced Salt  ','Navstel');
Insert into Medication values ('m-20', 'Balsalazide ','Colazal');
Insert into Medication values ('m-21', 'Flumequine','Flubactin');
Insert into Medication values ('m-22', 'Nalidixic acid','NegGam');
Insert into Medication values ('m-23', 'Oxolinic acid','Uroxin');
Insert into Medication values ('m-24', 'Piromidic acid','Panacid');
Insert into Medication values ('m-25', 'Pipemidic acid','Dolcol');
Insert into Medication values ('m-26', 'Rosoxacin','Eradacil');
Insert into Medication values ('m-27', 'Ciprofloxacin','Cipro XR');
Insert into Medication values ('m-28', 'Enoxacin','Enroxil');
Insert into Medication values ('m-29', 'Lomefloxacin','Maxaquin');
Insert into Medication values ('m-30', 'Nadifloxacin','Acuatim');
Insert into Medication values ('m-31', 'Norfloxacin','Lexinor');
Insert into Medication values ('m-32', 'Ofloxacin','Floxin');
Insert into Medication values ('m-33', 'Pefloxacin','Peflacine');
Insert into Medication values ('m-34', 'Rufloxacin','Uroflox');
Insert into Medication values ('m-35', 'Balofloxacin','Baloxin');
Insert into Medication values ('m-36', 'Gatifloxacin','Tequin, Zymar');
Insert into Medication values ('m-37', 'Grepafloxacin','Raxar');
Insert into Medication values ('m-38', 'Levofloxacin','Cravit');
Insert into Medication values ('m-39', 'Moxifloxacin','Avelox');
Insert into Medication values ('m-40', 'Pazufloxacin','Pasil');
Insert into Medication values ('m-41', 'Sparfloxacin','Zagam');
Insert into Medication values ('m-42', 'Temafloxacin','Omniflox');
Insert into Medication values ('m-43', 'Tosufloxacin','Ozex, Tosacin');
Insert into Medication values ('m-44', 'Besifloxacin','Besivance');
Insert into Medication values ('m-45', 'Gemifloxacin','Factive');
Insert into Medication values ('m-46', 'Sitafloxacin','Gracevit');
Insert into Medication values ('m-47', 'Trovafloxacin','Trovan');
Insert into Medication values ('m-48', 'Prulifloxacin','Quisnon');
Insert into Medication values ('m-49', 'Demeclocycline','Declomycin');
Insert into Medication values ('m-50', 'Doxycycline','Doryx');
Insert into Medication values ('m-51', 'Minocycline','Dynacin');
Insert into Medication values ('m-52', 'Oxytetracycline','Terramycin');
Insert into Medication values ('m-53', 'Tetracycline','Achromycin');
Insert into Medication values ('m-54', 'Tigecycline','Tygacil');
Insert into Medication values ('m-55', 'Chloramphenicol','Chloromycetin');
Insert into Medication values ('m-56', 'Metronidazole','Flagyl');
Insert into Medication values ('m-57', 'Tinidazole','Tindamax');
Insert into Medication values ('m-58', 'Nitrofurantoin','Furadantin, Macrobid, Macrodantin');
Insert into Medication values ('m-59', 'Vancomycin','Vancocin');
Insert into Medication values ('m-60', 'Teicoplanin','Targocid');
Insert into Medication values ('m-61', 'Telavancin','Vibativ');
Insert into Medication values ('m-62', 'Linezolid','Zyvox');
Insert into Medication values ('m-63', 'Cycloserine','Seromycin');
Insert into Medication values ('m-64', 'Rifampin','Rifadin');
Insert into Medication values ('m-65', 'Rifabutin','Mycobutin');
Insert into Medication values ('m-66', 'Rifapentine','Priftin');
Insert into Medication values ('m-67', 'Rifalazil','Helidac ');
Insert into Medication values ('m-68', 'Bacitracin','Baciguent');
Insert into Medication values ('m-69', 'Polymyxin B','Metizol');
Insert into Medication values ('m-70', 'Viomycin',' Neo-Metric');
Insert into Medication values ('m-71', 'Capreomycin','Noritate');
Insert into Medication values ('m-72', 'Acyclovir','Zovirax, Sitavig');
Insert into Medication values ('m-73', 'Brivudine','Helpin');
Insert into Medication values ('m-74', 'Docosanol','Abreva');
Insert into Medication values ('m-75', 'Famciclovir','Famvir');
Insert into Medication values ('m-76', 'Foscarnet','Foscavir');
Insert into Medication values ('m-77', 'Idoxuridine','Herplex, Dendrid');
Insert into Medication values ('m-78', 'Penciclovir','Denavir');
Insert into Medication values ('m-79', 'Trifluridine','Viroptic');
Insert into Medication values ('m-80', 'Valacyclovir','Valtrex');
Insert into Medication values ('m-81', 'Clonidine','Catapres');
Insert into Medication values ('m-82', 'Guanabenz','Wytensin');
Insert into Medication values ('m-83', 'Guanfacine','Intuniv, Tenex');
Insert into Medication values ('m-84', 'Methyldopa','Aldomet');
Insert into Medication values ('m-85', 'Lofexidine','Britlofex');
Insert into Medication values ('m-86', 'Azilsartan','Edarbi');
Insert into Medication values ('m-87', 'Candesartan','Atacand');
Insert into Medication values ('m-88', 'Eprosartan','Teveten');
Insert into Medication values ('m-89', 'Irbesartan','Avapro');
Insert into Medication values ('m-90', 'Losartan','Cozaar');
Insert into Medication values ('m-91', 'Olmesartan','Benicar');
Insert into Medication values ('m-92', 'Telmisartan','Micardis');
Insert into Medication values ('m-93', 'Valsartan','Diovan');
Insert into Medication values ('m-94', 'Benazepril','Lotensin');
Insert into Medication values ('m-95', 'Captopril','Capoten');
Insert into Medication values ('m-96', 'Enalapril','Vasotec');
Insert into Medication values ('m-97', 'Fosinopril','Monopril');
Insert into Medication values ('m-98', 'Lisinopril','Prinivil');
Insert into Medication values ('m-99', 'Moexipril','Univasc');
Insert into Medication values ('m-100', 'Perindopril','Aceon');
