Insert into procedural values ('Pro-02', 'Ablation Therapy for Arrhythmias');
Insert into procedural values ('Pro-03', 'Ablation, Endometrial (Endometrial Ablation)');
Insert into procedural values ('Pro-04', 'Ablation, Uterus (Endometrial Ablation)');
Insert into procedural values ('Pro-05', 'Abnormal Liver Enzymes (Liver Blood Tests)');
Insert into procedural values ('Pro-06', 'Absorbent Products Incontinence (Urinary Incontinence Products for Men)');
Insert into procedural values ('Pro-07', 'Abstinence Method of Birth Control (Natural Methods of Birth Control)');
Insert into procedural values ('Pro-08', 'Acupuncture');
Insert into procedural values ('Pro-09', 'Adenoidectomy Surgical Instructions');
Insert into procedural values ('Pro-10', 'Adenosine (Exercise Stress Test)');
Insert into procedural values ('Pro-11', 'Adenosine Stress Test For Heart Disease (Coronary Artery Disease Screening Tests (CAD))');
Insert into procedural values ('Pro-12', 'AFP Blood Test (Alpha-fetoprotein Blood Test)');
Insert into procedural values ('Pro-13', 'Alexander Technique for Childbirth (Childbirth Class Options)');
Insert into procedural values ('Pro-14', 'ALK (Keratoplasty Eye Surgery (ALK))');
Insert into procedural values ('Pro-15', 'Allergy Shots');
Insert into procedural values ('Pro-16', 'Allergy, Skin Test (Skin Test For Allergy)');
Insert into procedural values ('Pro-17', 'Alpha-fetoprotein Blood Test');
Insert into procedural values ('Pro-18', 'ALT Test (Liver Blood Tests)');
Insert into procedural values ('Pro-19', 'AMA (Antimitochondrial Antibodies)');
Insert into procedural values ('Pro-20', 'Amino Acid, Homocysteine (Homocysteine)');
Insert into procedural values ('Pro-21', 'Amniocentesis');
Insert into procedural values ('Pro-22', 'Amniotic Fluid (Amniocentesis)');
Insert into procedural values ('Pro-23', 'ANA (Antinuclear Antibody)');
Insert into procedural values ('Pro-24', 'Analysis of Urine (Urinalysis)');
Insert into procedural values ('Pro-25', 'Angiogram Of Heart (Coronary Angiogram)');
Insert into procedural values ('Pro-26', 'Angioplasty (Coronary Angioplasty)');
Insert into procedural values ('Pro-27', 'Annulus Support (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-28', 'Anti-CCP (Citrulline Antibody)');
Insert into procedural values ('Pro-29', 'Anti-citrulline Antibody (Citrulline Antibody)');
Insert into procedural values ('Pro-30', 'Anti-cyclic Citrullinated Peptide Antibody (Citrulline Antibody)');
Insert into procedural values ('Pro-31', 'Anti-Reflux Surgery (Fundoplication)');
Insert into procedural values ('Pro-32', 'Antimicrosomal Antibody Test (Thyroid Peroxidase Test)');
Insert into procedural values ('Pro-33', 'Antimitochondrial Antibodies');
Insert into procedural values ('Pro-34', 'Antinuclear Antibody');
Insert into procedural values ('Pro-35', 'Antithyroid Microsomal Antibody Test (Thyroid Peroxidase Test)');
Insert into procedural values ('Pro-36', 'Antro-duodenal Motility Study');
Insert into procedural values ('Pro-37', 'Aortic Heart Valve Replacement (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-38', 'Apgar Score');
Insert into procedural values ('Pro-39', 'Appendectomy');
Insert into procedural values ('Pro-40', 'Arrhythmia Treatment (Ablation Therapy for Arrhythmias)');
Insert into procedural values ('Pro-41', 'Arthritis Physical and Occupational Therapy');
Insert into procedural values ('Pro-42', 'Arthrocentesis (Joint Aspiration)');
Insert into procedural values ('Pro-43', 'Arthroplasty (Joint Replacement Surgery Of The Hand)');
Insert into procedural values ('Pro-44', 'Arthroscopy');
Insert into procedural values ('Pro-45', 'Artificial Kidney (Hemodialysis)');
Insert into procedural values ('Pro-46', 'Aspiration, Joint (Joint Aspiration)');
Insert into procedural values ('Pro-47', 'AST Test (Liver Blood Tests)');
Insert into procedural values ('Pro-48', 'Astigmatic Keratotomy Eye Surgery');
Insert into procedural values ('Pro-49', 'Auditory Brainstem Response (Newborn Infant Hearing Screening)');
Insert into procedural values ('Pro-50', 'Augmentation, Lip (Lip Augmentation)');
Insert into procedural values ('Pro-51', 'Autism Screening and Diagnosis');
Insert into procedural values ('Pro-52', 'Autopsy');
Insert into procedural values ('Pro-53', 'Back Surgery (Minimally Invasive Lumbar Spinal Fusion)');
Insert into procedural values ('Pro-54', 'Baclofen Pump Therapy');
Insert into procedural values ('Pro-55', 'Bad Cholesterol Test (Cholesterol Test)');
Insert into procedural values ('Pro-56', 'Balloon Angioplasty Of Heart (Coronary Angioplasty)');
Insert into procedural values ('Pro-57', 'Balloon Endoscopy');
Insert into procedural values ('Pro-58', 'Balloon Enteroscopy (Balloon Endoscopy)');
Insert into procedural values ('Pro-59', 'Balloon Valvuloplasty (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-60', 'Barium Enema');
Insert into procedural values ('Pro-61', 'Barium Swallow (Upper GI Series)');
Insert into procedural values ('Pro-62', 'Barrier Methods of Birth Control');
Insert into procedural values ('Pro-63', 'Basal Body Temperature Method of Birth Control (Natural Methods of Birth Control)');
Insert into procedural values ('Pro-64', 'Bicarbonate (Electrolytes)');
Insert into procedural values ('Pro-65', 'Biliary Drainage (Duodenal Biliary Drainage)');
Insert into procedural values ('Pro-66', 'Bioelectric Therapy');
Insert into procedural values ('Pro-67', 'Biological Therapy');
Insert into procedural values ('Pro-68', 'Biological Valve (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-69', 'Biopsy Of Cervix (Colposcopy)');
Insert into procedural values ('Pro-70', 'Biopsy, Breast (Breast Biopsy)');
Insert into procedural values ('Pro-71', 'Biopsy, Liver (Liver Biopsy)');
Insert into procedural values ('Pro-72', 'Biotherapy (Biological Therapy)');
Insert into procedural values ('Pro-73', 'Birth Control Patch (Hormonal Methods of Birth Control)');
Insert into procedural values ('Pro-74', 'Birth Control Pills (Hormonal Methods of Birth Control)');
Insert into procedural values ('Pro-75', 'Birthing Classes (Pregnancy: Birthing and Parenting Classes)');
Insert into procedural values ('Pro-76', 'Biventricular Pacemaker');
Insert into procedural values ('Pro-77', 'Blepharoplasty (Eyelid Surgery)');
Insert into procedural values ('Pro-78', 'Blepharospasm Treatment, Botox (Botox Treatment)');
Insert into procedural values ('Pro-79', 'Blood Count (Complete Blood Count)');
Insert into procedural values ('Pro-80', 'Blood Liver Enzymes (Liver Blood Tests)');
Insert into procedural values ('Pro-81', 'Blood Test, Ferritin (Ferritin Blood Test)');
Insert into procedural values ('Pro-82', 'Blood Test, Thyroid (Thyroid Blood Tests)');
Insert into procedural values ('Pro-83', 'Blood Transfusion');
Insert into procedural values ('Pro-84', 'Blood White Cell Count (Complete Blood Count)');
Insert into procedural values ('Pro-85', 'Blood, Bicarbonate (Electrolytes)');
Insert into procedural values ('Pro-86', 'Blood, Chloride (Electrolytes)');
Insert into procedural values ('Pro-87', 'Blood, CO2 (Electrolytes)');
Insert into procedural values ('Pro-88', 'Blood, Electrolytes (Electrolytes)');
Insert into procedural values ('Pro-89', 'Blood, Hematocrit (Complete Blood Count)');
Insert into procedural values ('Pro-90', 'Blood, Hemoglobin (Complete Blood Count)');
Insert into procedural values ('Pro-91', 'Blood, Platelet Count (Complete Blood Count)');
Insert into procedural values ('Pro-92', 'Blood, Potassium (Electrolytes)');
Insert into procedural values ('Pro-93', 'Blood, Red Cell Count (Complete Blood Count)');
Insert into procedural values ('Pro-94', 'Blood, Sodium (Electrolytes)');
Insert into procedural values ('Pro-95', 'Blue Light Therapy (Photodynamic Therapy)');
Insert into procedural values ('Pro-96', 'Bone Density Scan');
Insert into procedural values ('Pro-97', 'Bone Marrow');
Insert into procedural values ('Pro-98', 'Bone Marrow Transplant (Peripheral Blood Stem Cell Transplant)');
Insert into procedural values ('Pro-99', 'Bone Marrow Transplantation for Breast Cancer');
Insert into procedural values ('Pro-100', 'Botox Injections (Botox Treatment)');
Insert into procedural values ('Pro-101', 'Botox to Treat Multiple Sclerosis (MS)');
Insert into procedural values ('Pro-102', 'Botox Treatment');
Insert into procedural values ('Pro-103', 'Botox Treatment (Botox Treatment)');
Insert into procedural values ('Pro-104', 'Bowel Diversion Surgery Ileostomy, Colostomy');
Insert into procedural values ('Pro-105', 'Brachytherapy');
Insert into procedural values ('Pro-106', 'Bradley Method for Childbirth (Childbirth Class Options)');
Insert into procedural values ('Pro-107', 'Brain Wave Test (EEG - Electroencephalogram)');
Insert into procedural values ('Pro-108', 'Breast Augmentation');
Insert into procedural values ('Pro-109', 'Breast Biopsy');
Insert into procedural values ('Pro-110', 'Breast Cancer Follow-Up Self-Exam');
Insert into procedural values ('Pro-111', 'Breast Cancer Genetic Testing (Genetic Testing for Breast Cancer)');
Insert into procedural values ('Pro-112', 'Breast Implants (Breast Augmentation)');
Insert into procedural values ('Pro-113', 'Breast Reconstruction');
Insert into procedural values ('Pro-114', 'Breast Reconstruction Without Implants');
Insert into procedural values ('Pro-115', 'Breast Reduction');
Insert into procedural values ('Pro-116', 'Breast Self Exam');
Insert into procedural values ('Pro-117', 'Breastfeeding Classes (Pregnancy: Birthing and Parenting Classes)');
Insert into procedural values ('Pro-118', 'Breath Test, Hydrogen (Hydrogen Breath Test)');
Insert into procedural values ('Pro-119', 'Breath Test, Urea (Urea Breath Test)');
Insert into procedural values ('Pro-120', 'Breathing Tube (Endotracheal Intubation)');
Insert into procedural values ('Pro-121', 'Bridges');
Insert into procedural values ('Pro-122', 'Bronchoscopy');
Insert into procedural values ('Pro-123', 'Brow Lift Cosmetic Surgery');
Insert into procedural values ('Pro-124', 'Bypass Surgery, Heart (Coronary Artery Bypass Graft)');
Insert into procedural values ('Pro-125', 'Bypass, Stomach (Gastric Bypass Surgery)');
Insert into procedural values ('Pro-126', 'C-Reactive Protein Test (CRP)');
Insert into procedural values ('Pro-127', 'C-Section (Cesarean Birth)');
Insert into procedural values ('Pro-128', 'CA 125');
Insert into procedural values ('Pro-129', 'CABG (Coronary Artery Bypass Graft)');
Insert into procedural values ('Pro-130', 'Calendar Rhythm Method of Birth Control (Natural Methods of Birth Control)');
Insert into procedural values ('Pro-131', 'Cancer Detection');
Insert into procedural values ('Pro-132', 'Capsule Endoscopy');
Insert into procedural values ('Pro-133', 'Carcinoembryonic Antigen');
Insert into procedural values ('Pro-134', 'Cardiac Catheterization');
Insert into procedural values ('Pro-135', 'Cardiac Stress Test (Exercise Stress Test)');
Insert into procedural values ('Pro-136', 'Care, Prenatal (Pregnancy: Prenatal Care and Tests)');
Insert into procedural values ('Pro-137', 'Caring for a Continent Ileostomy');
Insert into procedural values ('Pro-138', 'Caring for Teeth With Braces or Retainers');
Insert into procedural values ('Pro-139', 'Caring for Your Dentures');
Insert into procedural values ('Pro-140', 'CAT Scan');
Insert into procedural values ('Pro-141', 'Cataract Surgery');
Insert into procedural values ('Pro-142', 'CBC (Complete Blood Count)');
Insert into procedural values ('Pro-143', 'CEA (Carcinoembryonic Antigen)');
Insert into procedural values ('Pro-144', 'Cervical Biopsy (Colposcopy)');
Insert into procedural values ('Pro-145', 'Cervical Cancer Screening Test (Pap Smear)');
Insert into procedural values ('Pro-146', 'Cervical Cancer Test (Cervista HPV Test)');
Insert into procedural values ('Pro-147', 'Cervical Cap (Barrier Methods of Birth Control)');
Insert into procedural values ('Pro-148', 'Cervista HPV Test');
Insert into procedural values ('Pro-149', 'Cervista HPV Test (Cervista HPV Test)');
Insert into procedural values ('Pro-150', 'Cesarean Birth (C-Section (Cesarean Birth))');
Insert into procedural values ('Pro-151', 'Cheek Implant (Chin, Cheek, and Jaw Implants)');
Insert into procedural values ('Pro-152', 'Chemical Peel');
Insert into procedural values ('Pro-153', 'Chemo Infusion and Chemoembolization of Liver');
Insert into procedural values ('Pro-154', 'Chemotherapy');
Insert into procedural values ('Pro-155', 'Chemotherapy Treatment for Breast Cancer');
Insert into procedural values ('Pro-156', 'Chest X-ray');
Insert into procedural values ('Pro-157', 'Childbirth Class Options');
Insert into procedural values ('Pro-158', 'childhood immunization schedule (Childhood Vaccination Schedule)');
Insert into procedural values ('Pro-159', 'Childhood Vaccination Schedule');
Insert into procedural values ('Pro-160', 'Chin, Cheek, and Jaw Implants');
Insert into procedural values ('Pro-161', 'Chloride (Electrolytes)');
Insert into procedural values ('Pro-162', 'Cholecystectomy');
Insert into procedural values ('Pro-163', 'Cholecystogram (Oral Cholecystogram)');
Insert into procedural values ('Pro-164', 'Cholescintigraphy');
Insert into procedural values ('Pro-165', 'Cholesterol Test');
Insert into procedural values ('Pro-166', 'Choosing a Toothbrush');
Insert into procedural values ('Pro-167', 'Choosing a Toothpaste');
Insert into procedural values ('Pro-168', 'Chordae & Papillary Muscles Repair (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-169', 'Chorionic Villus Sampling');
Insert into procedural values ('Pro-170', 'Circumcision The Medical Pros and Cons');
Insert into procedural values ('Pro-171', 'Circumcision The Surgical Procedure');
Insert into procedural values ('Pro-172', 'Citrulline Antibody');
Insert into procedural values ('Pro-173', 'Classes, Childbirth (Childbirth Class Options)');
Insert into procedural values ('Pro-174', 'Clinical Trials');
Insert into procedural values ('Pro-175', 'CNB (Breast Biopsy)');
Insert into procedural values ('Pro-176', 'CO2 (Electrolytes)');
Insert into procedural values ('Pro-177', 'Colitis Surgery (Ulcerative Colitis Surgery)');
Insert into procedural values ('Pro-178', 'Collagen and Injectable Fillers');
Insert into procedural values ('Pro-179', 'Colon Cancer Screening');
Insert into procedural values ('Pro-180', 'Colon Resection (Bowel Diversion Surgery Ileostomy, Colostomy)');
Insert into procedural values ('Pro-181', 'Colonoscopy');
Insert into procedural values ('Pro-182', 'Colonoscopy, Virtual (Virtual Colonoscopy)');
Insert into procedural values ('Pro-183', 'Colostomy (Bowel Diversion Surgery Ileostomy, Colostomy)');
Insert into procedural values ('Pro-184', 'Colostomy: A Patients Perspective');
Insert into procedural values ('Pro-185', 'Colposcopy');
Insert into procedural values ('Pro-186', 'Commissurotomy (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-187', 'Complete Blood Count');
Insert into procedural values ('Pro-188', 'Complete Dentures (Dentures)');
Insert into procedural values ('Pro-189', 'Computerized Axial Tomography (CAT Scan)');
Insert into procedural values ('Pro-190', 'Condoms');
Insert into procedural values ('Pro-191', 'Conization, Cervix (Colposcopy)');
Insert into procedural values ('Pro-192', 'Continent Ileostomy (Bowel Diversion Surgery Ileostomy, Colostomy)');
Insert into procedural values ('Pro-193', 'Contraceptive Measures After Unprotected Sex');
Insert into procedural values ('Pro-194', 'Contraceptive Sponge (Barrier Methods of Birth Control)');
Insert into procedural values ('Pro-195', 'Core Needle Breast Biopsy (Breast Biopsy)');
Insert into procedural values ('Pro-196', 'Coronary Angiogram');
Insert into procedural values ('Pro-197', 'Coronary Angioplasty');
Insert into procedural values ('Pro-198', 'Coronary Artery Bypass (Coronary Artery Bypass Graft)');
Insert into procedural values ('Pro-199', 'Coronary Artery Bypass Graft');
Insert into procedural values ('Pro-200', 'Coronary Artery Disease Screening Tests (CAD)');
Insert into procedural values ('Pro-201', 'Corpus Callosotomy (Surgical Options for Epilepsy)');
Insert into procedural values ('Pro-202', 'Cortisone Injection');
Insert into procedural values ('Pro-203', 'Cortisone Shot (Cortisone Injection)');
Insert into procedural values ('Pro-204', 'Cosmetic Surgery (Plastic Surgery (Cosmetic Surgery))');
Insert into procedural values ('Pro-205', 'Cosmetic Surgery - Lipoplasty (Lipoplasty (Ultrasonic Assisted))');
Insert into procedural values ('Pro-206', 'Cosmetic Surgery for Varicose and Spider Veins (Sclerotherapy)');
Insert into procedural values ('Pro-207', 'Cosmetic Surgery, Chemical Peel (Chemical Peel)');
Insert into procedural values ('Pro-208', 'Cosmetic Surgery, Collagen Injections (Collagen and Injectable Fillers)');
Insert into procedural values ('Pro-209', 'Cosmetic Surgery, Dermabrasion (Dermabrasion)');
Insert into procedural values ('Pro-210', 'Cosmetic Surgery, Lip Augmentation (Lip Augmentation)');
Insert into procedural values ('Pro-211', 'Cosmetic Surgery, Liposuction (Liposuction)');
Insert into procedural values ('Pro-212', 'Cosmetic Surgery, Neck Lift (Neck Lift Cosmetic Surgery)');
Insert into procedural values ('Pro-213', 'Costs, Prenatal (Pregnancy: Prenatal Care and Tests)');
Insert into procedural values ('Pro-214', 'Creatinine Blood Test');
Insert into procedural values ('Pro-215', 'CRP (C-Reactive Protein Test (CRP))');
Insert into procedural values ('Pro-216', 'Cryotherapy');
Insert into procedural values ('Pro-217', 'CT Colonosopy (Virtual Colonoscopy)');
Insert into procedural values ('Pro-218', 'CT Coronary Angiogram');
Insert into procedural values ('Pro-219', 'CT Scan (CAT Scan)');
Insert into procedural values ('Pro-220', 'CT, Ultrafast (Electron Beam Computerized Tomography)');
Insert into procedural values ('Pro-221', 'CVS (Chorionic Villus Sampling)');
Insert into procedural values ('Pro-222', 'Cystic Fibrosis Test (Sweat Chloride Test)');
Insert into procedural values ('Pro-223', 'Cystoscopy and Ureteroscopy');
Insert into procedural values ('Pro-224', 'D & C (Dilation and Curettage)');
Insert into procedural values ('Pro-225', 'Decalcification (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-226', 'Deep Brain Stimulation');
Insert into procedural values ('Pro-227', 'Defibrillator (Implantable Cardiac Defibrillator)');
Insert into procedural values ('Pro-228', 'Delivery of a Baby (Labor and Delivery)');
Insert into procedural values ('Pro-229', 'Dental (Fillings)');
Insert into procedural values ('Pro-230', 'Dental Bonding');
Insert into procedural values ('Pro-231', 'Dental Bridges (Bridges)');
Insert into procedural values ('Pro-232', 'Dental Care (Teeth and Gum Care)');
Insert into procedural values ('Pro-233', 'Dental Care for Babies');
Insert into procedural values ('Pro-234', 'Dental Crowns');
Insert into procedural values ('Pro-235', 'Dental Implants');
Insert into procedural values ('Pro-236', 'Dental Lasers (Lasers in Dental Care)');
Insert into procedural values ('Pro-237', 'Dental Sealants');
Insert into procedural values ('Pro-238', 'Dental Surgery (Oral Surgery)');
Insert into procedural values ('Pro-239', 'Dental Veneers');
Insert into procedural values ('Pro-240', 'Dental X-Rays');
Insert into procedural values ('Pro-241', 'Dental X-Rays: When to Get Them');
Insert into procedural values ('Pro-242', 'Dentures');
Insert into procedural values ('Pro-243', 'Dermabrasion');
Insert into procedural values ('Pro-244', 'Dermagraphics (Permanent Makeup (Micropigmentation))');
Insert into procedural values ('Pro-245', 'Detecting Hearing Loss in Children');
Insert into procedural values ('Pro-246', 'Developmental Screening');
Insert into procedural values ('Pro-247', 'DEXA (Bone Density Scan)');
Insert into procedural values ('Pro-248', 'Diabetes Urine Tests (Urine Tests for Diabetes)');
Insert into procedural values ('Pro-249', 'Dialysis');
Insert into procedural values ('Pro-250', 'Diaphragm, Birth Control (Barrier Methods of Birth Control)');
Insert into procedural values ('Pro-251', 'Dilation and Curettage');
Insert into procedural values ('Pro-252', 'Discogram');
Insert into procedural values ('Pro-253', 'Diversion Surgery, Bowel (Bowel Diversion Surgery Ileostomy, Colostomy)');
Insert into procedural values ('Pro-254', 'Dobutamine (Exercise Stress Test)');
Insert into procedural values ('Pro-255', 'Dobutamine Stress Test For Heart Disease (Coronary Artery Disease Screening Tests (CAD))');
Insert into procedural values ('Pro-256', 'Double Balloon Endoscopy (Balloon Endoscopy)');
Insert into procedural values ('Pro-257', 'Douche, Vaginal (Vaginal Douche (Douching))');
Insert into procedural values ('Pro-258', 'Douching and Urniation Method of Birth Control (Natural Methods of Birth Control)');
Insert into procedural values ('Pro-259', 'Drainage Bags for Incontinence (Urinary Incontinence Products for Men)');
Insert into procedural values ('Pro-260', 'Drug Infusion (IV Drug Infusion FAQs)');
Insert into procedural values ('Pro-261', 'Dual X-ray Absorptometry (Bone Density Scan)');
Insert into procedural values ('Pro-262', 'Duodenal Biliary Drainage');
Insert into procedural values ('Pro-263', 'Duodenoscopy (Endoscopy)');
Insert into procedural values ('Pro-264', 'DXA Scan (Bone Density Scan)');
Insert into procedural values ('Pro-265', 'EA (Endometrial Ablation)');
Insert into procedural values ('Pro-266', 'Ear Tubes');
Insert into procedural values ('Pro-267', 'Ear, Cosmetic Surgery (Otoplasty)');
Insert into procedural values ('Pro-268', 'ECG (Electrocardiogram (ECG or EKG))');
Insert into procedural values ('Pro-269', 'Echo (Echocardiogram)');
Insert into procedural values ('Pro-270', 'Echocardiogram');
Insert into procedural values ('Pro-271', 'Echogram (Ultrasound)');
Insert into procedural values ('Pro-272', 'ECT (Electroconvulsive Therapy)');
Insert into procedural values ('Pro-273', 'EEG - Electroencephalogram');
Insert into procedural values ('Pro-274', 'EGD (Endoscopy)');
Insert into procedural values ('Pro-275', 'EGG (Electrogastrogram)');
Insert into procedural values ('Pro-276', 'EKG (Electrocardiogram (ECG or EKG))');
Insert into procedural values ('Pro-277', 'Electrocardiogram (ECG or EKG)');
Insert into procedural values ('Pro-278', 'Electroconvulsive Therapy');
Insert into procedural values ('Pro-279', 'Electroencephalogram (EEG - Electroencephalogram)');
Insert into procedural values ('Pro-280', 'Electrogastrogram');
Insert into procedural values ('Pro-281', 'Electrolysis');
Insert into procedural values ('Pro-282', 'Electrolytes');
Insert into procedural values ('Pro-283', 'Electromyogram');
Insert into procedural values ('Pro-284', 'Electron Beam Computerized Tomography');
Insert into procedural values ('Pro-285', 'Electrophysiology Test');
Insert into procedural values ('Pro-286', 'Electroretinography');
Insert into procedural values ('Pro-287', 'Electrothermal Therapy (Transcutaneous Electrical Nerve Stimulation)');
Insert into procedural values ('Pro-288', 'Elevated Homocysteine (Homocysteine)');
Insert into procedural values ('Pro-289', 'ELISA Tests');
Insert into procedural values ('Pro-290', 'EMG (Electromyogram)');
Insert into procedural values ('Pro-291', 'Empyting Study, Gastric (Gastric Emptying Study)');
Insert into procedural values ('Pro-292', 'Endometrial Ablation');
Insert into procedural values ('Pro-293', 'Endometrial Biopsy');
Insert into procedural values ('Pro-294', 'Endoscopic Retrograde Cholangio-Pancreatography (ERCP)');
Insert into procedural values ('Pro-295', 'Endoscopic Ultrasound');
Insert into procedural values ('Pro-296', 'Endoscopy');
Insert into procedural values ('Pro-297', 'Endoscopy, Balloon (Balloon Endoscopy)');
Insert into procedural values ('Pro-298', 'Endoscopy, Capsule (Capsule Endoscopy)');
Insert into procedural values ('Pro-299', 'Endoscopy, Upper Gastrointestinal (Endoscopy)');
Insert into procedural values ('Pro-300', 'Endotracheal Intubation');
Insert into procedural values ('Pro-301', 'Enema, Barium (Barium Enema)');
Insert into procedural values ('Pro-302', 'Enhancement, Lip (Lip Augmentation)');
Insert into procedural values ('Pro-303', 'Enteroscopy, Balloon (Balloon Endoscopy)');
Insert into procedural values ('Pro-304', 'Epidural Steroid Injection');
Insert into procedural values ('Pro-305', 'Epilepsy Surgery (Surgical Options for Epilepsy)');
Insert into procedural values ('Pro-306', 'Epilepsy Surgery, Children (Pediatric Epilepsy Surgery)');
Insert into procedural values ('Pro-307', 'Epilepsy Surgery, Multiple Subpial Transection (Multiple Subpial Transection)');
Insert into procedural values ('Pro-308', 'Epilepsy Test (EEG - Electroencephalogram)');
Insert into procedural values ('Pro-309', 'Epilepsy Treatment');
Insert into procedural values ('Pro-310', 'Episiotomy');
Insert into procedural values ('Pro-311', 'EPO (Erythropoietin)');
Insert into procedural values ('Pro-312', 'ERCP');
Insert into procedural values ('Pro-313', 'Erectile Dysfunction, Testosterone (Testosterone Therapy to Treat ED)');
Insert into procedural values ('Pro-314', 'ERG (Electroretinography)');
Insert into procedural values ('Pro-315', 'Erythrocyte Sedimentation Rate (Sedimentation Rate)');
Insert into procedural values ('Pro-316', 'Erythropheresis (Hemapheresis)');
Insert into procedural values ('Pro-317', 'Erythropoietin');
Insert into procedural values ('Pro-318', 'Esophageal Manometry');
Insert into procedural values ('Pro-319', 'Esophageal Motility Study (Esophageal Manometry)');
Insert into procedural values ('Pro-320', 'Esophageal pH Monitoring');
Insert into procedural values ('Pro-321', 'Esophageal pH Test (Esophageal pH Monitoring)');
Insert into procedural values ('Pro-322', 'Esophagogastroduodenoscopy (Endoscopy)');
Insert into procedural values ('Pro-323', 'Esophagoscopy (Endoscopy)');
Insert into procedural values ('Pro-324', 'ESR (Sedimentation Rate)');
Insert into procedural values ('Pro-325', 'Estrogen Replacement (Hormone Therapy)');
Insert into procedural values ('Pro-326', 'Estrogen Replacement Therapy (Hormone Therapy)');
Insert into procedural values ('Pro-327', 'ET (Hormone Therapy)');
Insert into procedural values ('Pro-328', 'EUS (Endoscopic Ultrasound)');
Insert into procedural values ('Pro-329', 'Exam, Breast (Breast Self Exam)');
Insert into procedural values ('Pro-330', 'Exam, Pelvic (Pelvic Exam)');
Insert into procedural values ('Pro-331', 'Excision Breast Biopsy (Breast Biopsy)');
Insert into procedural values ('Pro-332', 'Exercise Cardiac Stress Test (Coronary Artery Disease Screening Tests (CAD))');
Insert into procedural values ('Pro-333', 'Exercise Stress Test');
Insert into procedural values ('Pro-334', 'External Catheters for Incontinence (Urinary Incontinence Products for Men)');
Insert into procedural values ('Pro-335', 'Extratemporal Cortical Resection');
Insert into procedural values ('Pro-336', 'Eye Pressure Measurement (Tonometry)');
Insert into procedural values ('Pro-337', 'Eyebrow Lift (Brow Lift Cosmetic Surgery)');
Insert into procedural values ('Pro-338', 'Eyelid Surgery (Blepharoplasty (Eyelid Surgery))');
Insert into procedural values ('Pro-339', 'Face Lift');
Insert into procedural values ('Pro-340', 'Fallopian Tube Removal (Hysterectomy)');
Insert into procedural values ('Pro-341', 'FANA (Antinuclear Antibody)');
Insert into procedural values ('Pro-342', 'Fecal Occult Blood Tests');
Insert into procedural values ('Pro-343', 'Female Condom (Barrier Methods of Birth Control)');
Insert into procedural values ('Pro-344', 'Ferritin Blood Test');
Insert into procedural values ('Pro-345', 'Fillings');
Insert into procedural values ('Pro-346', 'Fine Needle Aspiration Breast Biopsy (Breast Biopsy)');
Insert into procedural values ('Pro-347', 'Fine-Needle Aspiration Biopsy of the Thyroid');
Insert into procedural values ('Pro-348', 'First Aid for Seizures');
Insert into procedural values ('Pro-349', 'Flexible Sigmoidoscopy');
Insert into procedural values ('Pro-350', 'Flu Shot Pregnancy (Pregnancy Flu Shot Side Effects and Safety)');
Insert into procedural values ('Pro-351', 'Flu Shot Pregnancy Side Effects (Pregnancy Flu Shot Side Effects and Safety)');
Insert into procedural values ('Pro-352', 'Flu Vaccination');
Insert into procedural values ('Pro-353', 'Fluorescent Antinuclear Antibody (Antinuclear Antibody)');
Insert into procedural values ('Pro-354', 'FNAB (Breast Biopsy)');
Insert into procedural values ('Pro-355', 'Freeze Nerves (Cryotherapy)');
Insert into procedural values ('Pro-356', 'Functional Hemispherectomy (Surgical Options for Epilepsy)');
Insert into procedural values ('Pro-357', 'Fundoplication');
Insert into procedural values ('Pro-358', 'Fusion, Lumbar (Minimally Invasive Lumbar Spinal Fusion');
Insert into procedural values ('Pro-359', 'Gallbladder Scan (Cholescintigraphy)');
Insert into procedural values ('Pro-360', 'Gallbladder x-ray (Oral Cholecystogram)');
Insert into procedural values ('Pro-361', 'Gardasil HPV Vaccine');
Insert into procedural values ('Pro-362', 'GAS Test (Rapid Strep Test)');
Insert into procedural values ('Pro-363', 'Gastric Banding Surgery (Lap Band Surgery (Gastric Banding))');
Insert into procedural values ('Pro-364', 'Gastric Bypass Surgery');
Insert into procedural values ('Pro-365', 'Gastric Emptying Study');
Insert into procedural values ('Pro-366', 'Gastroesophageal Reflux Disease Test (Esophageal pH Monitoring)');
Insert into procedural values ('Pro-367', 'Gastroscopy (Endoscopy)');
Insert into procedural values ('Pro-368', 'Genetic Testing for Breast Cancer');
Insert into procedural values ('Pro-369', 'GERD Surgery (Fundoplication)');
Insert into procedural values ('Pro-370', 'GERD Test (Esophageal pH Monitoring)');
Insert into procedural values ('Pro-371', 'Glucose Tolerance Test');
Insert into procedural values ('Pro-372', 'Good Cholesterol Test (Cholesterol Test)');
Insert into procedural values ('Pro-373', 'GTT (Glucose Tolerance Test)');
Insert into procedural values ('Pro-374', 'H&H (Hematocrit)');
Insert into procedural values ('Pro-375', 'Hair Removal');
Insert into procedural values ('Pro-376', 'Hand Surgery (Joint Replacement Surgery Of The Hand)');
Insert into procedural values ('Pro-377', 'Hb (Hemoglobin)');
Insert into procedural values ('Pro-378', 'Hct (Hematocrit)');
Insert into procedural values ('Pro-379', 'HCV (PCR (Polymerase Chain Reaction))');
Insert into procedural values ('Pro-380', 'HCV PCR (PCR (Polymerase Chain Reaction))');
Insert into procedural values ('Pro-381', 'HDL Cholesterol Test (Cholesterol Test)');
Insert into procedural values ('Pro-382', 'Hearing Testing of Newborns (Newborn Infant Hearing Screening)');
Insert into procedural values ('Pro-383', 'Heart Bypass (Coronary Artery Bypass Graft)');
Insert into procedural values ('Pro-384', 'Heart Disease, Testing For (Coronary Artery Disease Screening Tests (CAD))');
Insert into procedural values ('Pro-385', 'Heart Lead Extraction');
Insert into procedural values ('Pro-386', 'Heart Transplant');
Insert into procedural values ('Pro-387', 'Heart Valve Disease Treatment');
Insert into procedural values ('Pro-388', 'Helicobacter Pylori Breath Test (Urea Breath Test)');
Insert into procedural values ('Pro-389', 'Hemapheresis');
Insert into procedural values ('Pro-390', 'Hematocrit');
Insert into procedural values ('Pro-391', 'Hemodialysis');
Insert into procedural values ('Pro-392', 'Hemodialysis (Dialysis)');
Insert into procedural values ('Pro-393', 'Hemoglobin');
Insert into procedural values ('Pro-394', 'Hemoglobin A1c Test');
Insert into procedural values ('Pro-395', 'Hemorrhoidectomy, Stapled (Stapled Hemorrhoidectomy)');
Insert into procedural values ('Pro-396', 'Hgb (Hemoglobin)');
Insert into procedural values ('Pro-397', 'HIDA Scan (Cholescintigraphy)');
Insert into procedural values ('Pro-398', 'High Triglycerides (Triglyceride Test)');
Insert into procedural values ('Pro-399', 'Hip Replacement (Total Hip Replacement)');
Insert into procedural values ('Pro-400', 'HIV Testing');
Insert into procedural values ('Pro-401', 'Home Pregnancy Tests (Pregnancy Test)');
Insert into procedural values ('Pro-402', 'Homocysteine');
Insert into procedural values ('Pro-403', 'Homocystinuria (Homocysteine)');
Insert into procedural values ('Pro-404', 'Homograft Valve (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-405', 'Hormonal Methods of Birth Control');
Insert into procedural values ('Pro-406', 'Hormone Replacement Therapy (Hormone Therapy)');
Insert into procedural values ('Pro-407', 'Hormone Therapy');
Insert into procedural values ('Pro-408', 'HRT (Hormone Therapy)');
Insert into procedural values ('Pro-409', 'Human Papillomavirus Test (Cervista HPV Test)');
Insert into procedural values ('Pro-410', 'Hydrogen Breath Test');
Insert into procedural values ('Pro-411', 'HypnoBirthing for Childbirth (Childbirth Class Options)');
Insert into procedural values ('Pro-412', 'Hysterectomy');
Insert into procedural values ('Pro-413', 'Hysterectomy, Vaginal Assisted (Laparoscopically Assisted Vaginal Hysterectomy)');
Insert into procedural values ('Pro-414', 'Hysteroscopic Sterilization (Surgical Sterilization)');
Insert into procedural values ('Pro-415', 'Hysteroscopy');
Insert into procedural values ('Pro-416', 'ICD (Implantable Cardiac Defibrillator)');
Insert into procedural values ('Pro-417', 'Ileoanal Reservoir (Bowel Diversion Surgery Ileostomy, Colostomy)');
Insert into procedural values ('Pro-418', 'Ileostomy (Bowel Diversion Surgery Ileostomy, Colostomy)');
Insert into procedural values ('Pro-419', 'Ileostomy (Ulcerative Colitis Surgery)');
Insert into procedural values ('Pro-420', 'Imaging Colonoscopy (Virtual Colonoscopy)');
Insert into procedural values ('Pro-421', 'Immunization, Flu (Flu Vaccination)');
Insert into procedural values ('Pro-422', 'Immunizations');
Insert into procedural values ('Pro-423', 'Immunotherapy (Biological Therapy)');
Insert into procedural values ('Pro-424', 'Implantable Cardiac Defibrillator');
Insert into procedural values ('Pro-425', 'Incontinence Products for Men (Urinary Incontinence Products for Men)');
Insert into procedural values ('Pro-426', 'Influenza Immunization (Flu Vaccination)');
Insert into procedural values ('Pro-427', 'Infusion (IV Drug Infusion FAQs)');
Insert into procedural values ('Pro-428', 'Injection of Soft Tissues and Joints (Cortisone Injection)');
Insert into procedural values ('Pro-429', 'Injection, Trigger Point (Trigger Point Injection)');
Insert into procedural values ('Pro-430', 'Instructions for Sinus Surgery (Sinus Surgery)');
Insert into procedural values ('Pro-431', 'Insulin Pump For Diabetes Mellitus');
Insert into procedural values ('Pro-432', 'Intervenous Infusion (IV Drug Infusion FAQs)');
Insert into procedural values ('Pro-433', 'Intramuscular Electromyogram (Electromyogram)');
Insert into procedural values ('Pro-434', 'Intrauterine Device (IUD)');
Insert into procedural values ('Pro-435', 'Intravenous Cholangiogram');
Insert into procedural values ('Pro-436', 'Intubation (Endotracheal Intubation)');
Insert into procedural values ('Pro-437', 'Islet Cell Transplantation');
Insert into procedural values ('Pro-438', 'IUD');
Insert into procedural values ('Pro-439', 'IV Drug Infusion FAQs');
Insert into procedural values ('Pro-440', 'IVC (Intravenous Cholangiogram)');
Insert into procedural values ('Pro-441', 'Labor and Delivery');
Insert into procedural values ('Pro-442', 'Lactation Infertility (Natural Methods of Birth Control)');
Insert into procedural values ('Pro-443', 'Lactose Tolerance Test');
Insert into procedural values ('Pro-444', 'Lactose Tolerance Test for Infants (Stool Acidity Test)');
Insert into procedural values ('Pro-445', 'Lamaz Technique for Childbirth (Childbirth Class Options)');
Insert into procedural values ('Pro-446', 'Lap Band Surgery (Gastric Banding)');
Insert into procedural values ('Pro-447', 'Laparoscopic Liver Biopsy (Liver Biopsy)');
Insert into procedural values ('Pro-448', 'Laparoscopic Supra Cervical Hysterectomy (Hysterectomy)');
Insert into procedural values ('Pro-449', 'Laparoscopically Assisted Vaginal Hysterectomy');
Insert into procedural values ('Pro-450', 'Laparoscopy');
Insert into procedural values ('Pro-451', 'Laparoscopy-Assisted Vaginal Hysterectomy (Hysterectomy)');
Insert into procedural values ('Pro-452', 'LASEK Laser Eye Surgery');
Insert into procedural values ('Pro-453', 'Laser Resurfacing');
Insert into procedural values ('Pro-454', 'Laser Thermokeratoplasty (LTK Laser Eye Surgery)');
Insert into procedural values ('Pro-455', 'Lasers in Dental Care');
Insert into procedural values ('Pro-456', 'LASIK (LASIK Eye Surgery)');
Insert into procedural values ('Pro-457', 'LASIK Eye Surgery');
Insert into procedural values ('Pro-458', 'LAVH (Laparoscopically Assisted Vaginal Hysterectomy)');
Insert into procedural values ('Pro-459', 'LDL Cholesterol Test (Cholesterol Test)');
Insert into procedural values ('Pro-460', 'LEEP (Loop Electrosurgical Excision Procedure)');
Insert into procedural values ('Pro-461', 'Left Ventricular Assist Device (LVAD)');
Insert into procedural values ('Pro-462', 'Lesionectomy');
Insert into procedural values ('Pro-463', 'Leukapheresis (Hemapheresis)');
Insert into procedural values ('Pro-464', 'Leukopheresis (Hemapheresis)');
Insert into procedural values ('Pro-465', 'Lip Augmentation');
Insert into procedural values ('Pro-466', 'Lipid Panel (Triglyceride Test)');
Insert into procedural values ('Pro-467', 'Lipoplasty (Ultrasonic Assisted)');
Insert into procedural values ('Pro-468', 'Lipoprotein Panel (Triglyceride Test)');
Insert into procedural values ('Pro-469', 'Liposculpture (Liposuction)');
Insert into procedural values ('Pro-470', 'Liposuction');
Insert into procedural values ('Pro-471', 'Liver Biopsy');
Insert into procedural values ('Pro-472', 'Liver Blood Tests');
Insert into procedural values ('Pro-473', 'Liver Enzymes (Liver Blood Tests)');
Insert into procedural values ('Pro-474', 'Liver Resection');
Insert into procedural values ('Pro-475', 'Liver Transplant');
Insert into procedural values ('Pro-476', 'Liver-Related Procedures and Tests');
Insert into procedural values ('Pro-477', 'Lobe Resection (Surgical Options for Epilepsy)');
Insert into procedural values ('Pro-478', 'Loop Electrosurgical Excision Procedure');
Insert into procedural values ('Pro-479', 'Lower GI (Barium Enema)');
Insert into procedural values ('Pro-480', 'LP (Lumbar Puncture)');
Insert into procedural values ('Pro-481', 'LTK Laser Eye Surgery');
Insert into procedural values ('Pro-482', 'Lumbar Puncture');
Insert into procedural values ('Pro-483', 'Lumbar Spinal Fusion (Minimally Invasive Lumbar Spinal Fusion)');
Insert into procedural values ('Pro-484', 'Lumpectomy (Breast Biopsy)');
Insert into procedural values ('Pro-485', 'Lymph Node Biopsy, Sentinel (Sentinel Lymph Node Biopsy)');
Insert into procedural values ('Pro-486', 'Lymphapheresis (Hemapheresis)');
Insert into procedural values ('Pro-487', 'Lymphopheresis (Hemapheresis)');
Insert into procedural values ('Pro-488', 'M2 Antigen (Antimitochondrial Antibodies)');
Insert into procedural values ('Pro-489', 'Magnetic Resonance Imaging (MRI Scan)');
Insert into procedural values ('Pro-490', 'Mammogram');
Insert into procedural values ('Pro-491', 'Mammography (Mammogram)');
Insert into procedural values ('Pro-492', 'Manometry, Esophageal (Esophageal Manometry)');
Insert into procedural values ('Pro-493', 'Marrow (Bone Marrow)');
Insert into procedural values ('Pro-494', 'Marrow Transplant (Peripheral Blood Stem Cell Transplant)');
Insert into procedural values ('Pro-495', 'MCH (Complete Blood Count)');
Insert into procedural values ('Pro-496', 'MCHC (Complete Blood Count)');
Insert into procedural values ('Pro-497', 'MCV (Complete Blood Count)');
Insert into procedural values ('Pro-498', 'Mean Cell Hemoglobin (Complete Blood Count)');
Insert into procedural values ('Pro-499', 'Mean Cell Hemoglobin Concentration (Complete Blood Count)');
Insert into procedural values ('Pro-500', 'Mean Cell Volume (Complete Blood Count)');
Insert into procedural values ('Pro-501', 'Mean Platelet Volume (Complete Blood Count)');
Insert into procedural values ('Pro-502', 'Mechanical Valve (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-503', 'Medication Infusion (IV Drug Infusion FAQs)');
Insert into procedural values ('Pro-504', 'Microdermabrasion');
Insert into procedural values ('Pro-505', 'Micropigmentation (Permanent Makeup (Micropigmentation))');
Insert into procedural values ('Pro-506', 'Milk Tolerance Test (Lactose Tolerance Test)');
Insert into procedural values ('Pro-507', 'Minimally Invasive Lumbar Spinal Fusion');
Insert into procedural values ('Pro-508', 'Mohs Surgery');
Insert into procedural values ('Pro-509', 'Monitoring, Esophageal pH Test (Esophageal pH Monitoring)');
Insert into procedural values ('Pro-510', 'Morning after Pill (Contraceptive Measures After Unprotected Sex)');
Insert into procedural values ('Pro-511', 'Motility Study, Antro-duodenal (Antro-duodenal Motility Study)');
Insert into procedural values ('Pro-512', 'Motility, Esophageal Study (Esophageal Manometry)');
Insert into procedural values ('Pro-513', 'Mouth Guards');
Insert into procedural values ('Pro-514', 'MPV (Complete Blood Count)');
Insert into procedural values ('Pro-515', 'MRI Scan');
Insert into procedural values ('Pro-516', 'Mucus Inspection Method of Birth Control (Natural Methods of Birth Control)');
Insert into procedural values ('Pro-517', 'Multiple Subpial Transection');
Insert into procedural values ('Pro-518', 'Myocardial Biopsy');
Insert into procedural values ('Pro-519', 'Myogram (Electromyogram)');
Insert into procedural values ('Pro-520', 'Myringotomy (Ear Tubes)');
Insert into procedural values ('Pro-521', 'Nasal Airway Surgery');
Insert into procedural values ('Pro-522', 'Natural Methods of Birth Control');
Insert into procedural values ('Pro-523', 'NCV (Nerve Conduction Velocity Test)');
Insert into procedural values ('Pro-524', 'Nebulizer for Asthma');
Insert into procedural values ('Pro-525', 'Neck Lift Cosmetic Surgery');
Insert into procedural values ('Pro-526', 'Necropsy (Autopsy)');
Insert into procedural values ('Pro-527', 'Nerve Blocks');
Insert into procedural values ('Pro-528', 'Nerve Conduction Velocity Test');
Insert into procedural values ('Pro-529', 'Nerve Freezing (Cryotherapy)');
Insert into procedural values ('Pro-530', 'Newborn Infant Hearing Screening');
Insert into procedural values ('Pro-531', 'Newborn Score (Apgar Score)');
Insert into procedural values ('Pro-532', 'Normal Labor and Delivery (Labor and Delivery)');
Insert into procedural values ('Pro-533', 'Occult Fecal Blood Test (Fecal Occult Blood Tests)');
Insert into procedural values ('Pro-534', 'Occupational Therapy for Arthritis (Arthritis Physical and Occupational Therapy)');
Insert into procedural values ('Pro-535', 'OCPs (Hormonal Methods of Birth Control)');
Insert into procedural values ('Pro-536', 'OGTT (Glucose Tolerance Test)');
Insert into procedural values ('Pro-537', 'Oophorectomy (Hysterectomy)');
Insert into procedural values ('Pro-538', 'Oral Care (Teeth and Gum Care)');
Insert into procedural values ('Pro-539', 'Oral Cholecystogram');
Insert into procedural values ('Pro-540', 'Oral Glucose Tolerance Test (Glucose Tolerance Test)');
Insert into procedural values ('Pro-541', 'Oral Surgery');
Insert into procedural values ('Pro-542', 'OT for Arthritis (Arthritis Physical and Occupational Therapy)');
Insert into procedural values ('Pro-543', 'Otoacoustic Emission (Newborn Infant Hearing Screening)');
Insert into procedural values ('Pro-544', 'Otoplasty');
Insert into procedural values ('Pro-545', 'Ovary Removal (Hysterectomy)');
Insert into procedural values ('Pro-546', 'Ovulation Indicator Testing Kits (Natural Methods of Birth Control)');
Insert into procedural values ('Pro-547', 'Oximetry');
Insert into procedural values ('Pro-548', 'Pacemaker');
Insert into procedural values ('Pro-549', 'Pads for Urinary Incontinence (Urinary Incontinence Products for Men)');
Insert into procedural values ('Pro-550', 'Pap Smear');
Insert into procedural values ('Pro-551', 'Pap Test (Pap Smear)');
Insert into procedural values ('Pro-552', 'Papillomavirus, Human Test (Cervista HPV Test)');
Insert into procedural values ('Pro-553', 'Parathyroidectomy');
Insert into procedural values ('Pro-554', 'Parenting Classes (Pregnancy: Birthing and Parenting Classes)');
Insert into procedural values ('Pro-555', 'Partial Dentures (Dentures)');
Insert into procedural values ('Pro-556', 'Partial Hysterectomy (Hysterectomy)');
Insert into procedural values ('Pro-557', 'Patched Leaflets (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-558', 'PCI (Coronary Angioplasty)');
Insert into procedural values ('Pro-559', 'PCR (Polymerase Chain Reaction)');
Insert into procedural values ('Pro-560', 'PCV7 (Pneumococcal Vaccination)');
Insert into procedural values ('Pro-561', 'PDC-E2 Antigen (Antimitochondrial Antibodies)');
Insert into procedural values ('Pro-562', 'PDT (Photodynamic Therapy)');
Insert into procedural values ('Pro-563', 'Pediatric Epilepsy Surgery');
Insert into procedural values ('Pro-564', 'PEG (Percutaneous Endoscopic Gastrostomy)');
Insert into procedural values ('Pro-565', 'Pelvic Exam');
Insert into procedural values ('Pro-566', 'Penile Clamps for Incontinence (Urinary Incontinence Products for Men)');
Insert into procedural values ('Pro-567', 'Penile Implants');
Insert into procedural values ('Pro-568', 'Penis Prosthesis');
Insert into procedural values ('Pro-569', 'Percutaneous Coronary Intervention (Coronary Angioplasty)');
Insert into procedural values ('Pro-570', 'Percutaneous Endoscopic Gastrostomy');
Insert into procedural values ('Pro-571', 'Percutaneous Ethanol Injection of Liver');
Insert into procedural values ('Pro-572', 'Percutaneous Liver Biopsy (Liver Biopsy)');
Insert into procedural values ('Pro-573', 'Percutaneous Transluminal Coronary Angioplasty (Coronary Angioplasty)');
Insert into procedural values ('Pro-574', 'Peripheral Blood Stem Cell Transplant');
Insert into procedural values ('Pro-575', 'Permanent Makeup (Micropigmentation)');
Insert into procedural values ('Pro-576', 'pH Monitoring, Esophageal (Esophageal pH Monitoring)');
Insert into procedural values ('Pro-577', 'Phakic Intraocular Lenses');
Insert into procedural values ('Pro-578', 'Pharmacologic Stress Test For Heart Disease (Coronary Artery Disease Screening Tests (CAD))');
Insert into procedural values ('Pro-579', 'Pheresis (Hemapheresis)');
Insert into procedural values ('Pro-580', 'Photodynamic Therapy');
Insert into procedural values ('Pro-581', 'Photorefractive Keratectomy');
Insert into procedural values ('Pro-582', 'Physical Therapy for Arthritis (Arthritis Physical and Occupational Therapy)');
Insert into procedural values ('Pro-583', 'Pinworm Test');
Insert into procedural values ('Pro-584', 'Plan B Contraception (Contraceptive Measures After Unprotected Sex)');
Insert into procedural values ('Pro-585', 'Plasmapheresis (Hemapheresis)');
Insert into procedural values ('Pro-586', 'Plastic Surgery (Cosmetic Surgery)');
Insert into procedural values ('Pro-587', 'Plastic Surgery, Collagen Injections (Collagen and Injectable Fillers)');
Insert into procedural values ('Pro-588', 'Plastic Surgery, Neck Lift (Neck Lift Cosmetic Surgery)');
Insert into procedural values ('Pro-589', 'Platelet Count (Complete Blood Count)');
Insert into procedural values ('Pro-590', 'Plateletcytapheresis (Hemapheresis)');
Insert into procedural values ('Pro-591', 'Plateletpheresis (Hemapheresis)');
Insert into procedural values ('Pro-592', 'Pneumococcal Immunization (Pneumococcal Vaccination)');
Insert into procedural values ('Pro-593', 'Pneumococcal Vaccination');
Insert into procedural values ('Pro-594', 'Polymerase Chain Reaction (PCR (Polymerase Chain Reaction))');
Insert into procedural values ('Pro-595', 'Post Mortem Examination (Autopsy)');
Insert into procedural values ('Pro-596', 'Potassium (Electrolytes)');
Insert into procedural values ('Pro-597', 'PPD Skin Test (Tuberculosis Skin Test (PPD Skin Test))');
Insert into procedural values ('Pro-598', 'pre-op questions (Surgery Questions)');
Insert into procedural values ('Pro-599', 'Pregnancy Flu Shot Risks (Pregnancy Flu Shot Side Effects and Safety)');
Insert into procedural values ('Pro-600', 'Pregnancy Flu Shot Side Effects (Pregnancy Flu Shot Side Effects and Safety)');
Insert into procedural values ('Pro-601', 'Pregnancy Flu Shot Side Effects and Safety');
Insert into procedural values ('Pro-602', 'Pregnancy Test');
Insert into procedural values ('Pro-603', 'Pregnancy Ultrasound (Prenatal Ultrasound)');
Insert into procedural values ('Pro-604', 'Pregnancy: Birthing and Parenting Classes');
Insert into procedural values ('Pro-605', 'Pregnancy: Prenatal Care and Tests');
Insert into procedural values ('Pro-606', 'Pregnancy: Quad Marker Screening Test (Quad Marker Screen Test)');
Insert into procedural values ('Pro-607', 'Prenatal Care (Pregnancy: Prenatal Care and Tests)');
Insert into procedural values ('Pro-608', 'Prenatal Costs (Pregnancy: Prenatal Care and Tests)');
Insert into procedural values ('Pro-609', 'Prenatal Diagnosis (Amniocentesis)');
Insert into procedural values ('Pro-610', 'Prenatal Tests (Pregnancy: Prenatal Care and Tests)');
Insert into procedural values ('Pro-611', 'Prenatal Ultrasound');
Insert into procedural values ('Pro-612', 'preoperative questions (Surgery Questions)');
Insert into procedural values ('Pro-613', 'Prevention of Flu During Pregnancy (Pregnancy Flu Shot Side Effects and Safety)');
Insert into procedural values ('Pro-614', 'Preventive Mastectomy');
Insert into procedural values ('Pro-615', 'PRK (Photorefractive Keratectomy)');
Insert into procedural values ('Pro-616', 'Problems With Dental Fillings');
Insert into procedural values ('Pro-617', 'Products for Incontinence in Men (Urinary Incontinence Products for Men)');
Insert into procedural values ('Pro-618', 'Prophylactic Mastectomy (Preventive Mastectomy)');
Insert into procedural values ('Pro-619', 'Prostate Cancer Screening');
Insert into procedural values ('Pro-620', 'Prostate Specific Antigen');
Insert into procedural values ('Pro-621', 'Prostate Specific Antigen (Prostate Specific Antigen)');
Insert into procedural values ('Pro-622', 'Proton Beam Therapy of Liver');
Insert into procedural values ('Pro-623', 'PSA (Prostate Specific Antigen)');
Insert into procedural values ('Pro-624', 'Psychotherapy');
Insert into procedural values ('Pro-625', 'PT for Arthritis (Arthritis Physical and Occupational Therapy)');
Insert into procedural values ('Pro-626', 'PTCA (Coronary Angioplasty)');
Insert into procedural values ('Pro-627', 'Pulmonic Heart Valve Replacement (Heart Valve Disease Treatment)');
Insert into procedural values ('Pro-628', 'Pulse Oximetry (Oximetry)');
Insert into procedural values ('Pro-629', 'Pump for Insulin (Insulin Pump For Diabetes Mellitus)');
Insert into procedural values ('Pro-630', 'Push Endoscopy');
Insert into procedural values ('Pro-631', 'PUVA Therapy (Photochemotherapy)');
